dependencies:
  - name: redis
    version: 3.8.1
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: postgresql
    version: 2.6.5
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
