apiVersion: v1
kind: Service
metadata:
  name: {{ template "redash.fullname" . }}-server
  labels:
    app: {{ template "redash.name" . }}
    chart: {{ template "redash.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    app: {{ template "redash.name" . }}
    release: {{ .Release.Name }}
    role: server
